#include "aethera/script_expr.hpp"

#include <cctype>
#include <string>

namespace aethera {
namespace {
std::string trim(std::string s){std::size_t a=0,b=s.size();while(a<b&&std::isspace(static_cast<unsigned char>(s[a])))++a;while(b>a&&std::isspace(static_cast<unsigned char>(s[b-1])))--b;return s.substr(a,b-a);}
bool parse_op(const std::string& s,CompareOp& op,std::size_t& pos){const char* ops[]={"==","!=","<=",">=","<",">"};for(const char* raw:ops){std::string x(raw);auto p=s.find(x);if(p==std::string::npos)continue;op=x=="=="?CompareOp::Equal:x=="!="?CompareOp::NotEqual:x=="<"?CompareOp::Less:x=="<="?CompareOp::LessEqual:x==">"?CompareOp::Greater:CompareOp::GreaterEqual;pos=p;return true;}return false;}
}
bool parse_script_value(const std::string& raw,ScriptValue& out){const std::string s=trim(raw);if(s=="true"){out=true;return true;}if(s=="false"){out=false;return true;}if(s.size()>=2&&((s.front()=='\"'&&s.back()=='\"')||(s.front()=='\''&&s.back()=='\''))){out=s.substr(1,s.size()-2);return true;}try{out=std::stof(s);return true;}catch(...){out=s;return !s.empty();}}
bool parse_expression(const std::string& source,ScriptExpression& expression){expression={};std::size_t pos=0;if(!parse_op(source,expression.op,pos))return false;expression.left=trim(source.substr(0,pos));if(expression.left.empty())return false;std::size_t width=(source.compare(pos,2,"==")==0||source.compare(pos,2,"!=")==0||source.compare(pos,2,"<=")==0||source.compare(pos,2,">=")==0)?2:1;if(!parse_script_value(source.substr(pos+width),expression.right))return false;expression.valid=true;return true;}
bool evaluate_expression(const ScriptExpression& expression,const std::unordered_map<std::string,ScriptValue>& variables,bool& result){result=false;if(!expression.valid)return false;auto it=variables.find(expression.left);if(it==variables.end())return false;const ScriptValue&a=it->second;const ScriptValue&b=expression.right;if(a.index()!=b.index())return false;if(const auto*x=std::get_if<float>(&a)){float y=std::get<float>(b);switch(expression.op){case CompareOp::Equal:result=*x==y;break;case CompareOp::NotEqual:result=*x!=y;break;case CompareOp::Less:result=*x<y;break;case CompareOp::LessEqual:result=*x<=y;break;case CompareOp::Greater:result=*x>y;break;case CompareOp::GreaterEqual:result=*x>=y;break;}return true;}if(const auto*x=std::get_if<bool>(&a)){bool y=std::get<bool>(b);if(expression.op==CompareOp::Equal)result=*x==y;else if(expression.op==CompareOp::NotEqual)result=*x!=y;else return false;return true;}const auto&x=std::get<std::string>(a);const auto&y=std::get<std::string>(b);switch(expression.op){case CompareOp::Equal:result=x==y;break;case CompareOp::NotEqual:result=x!=y;break;case CompareOp::Less:result=x<y;break;case CompareOp::LessEqual:result=x<=y;break;case CompareOp::Greater:result=x>y;break;case CompareOp::GreaterEqual:result=x>=y;break;}return true;}
} // namespace aethera
